import Head from "next/head";
import { Inter } from "next/font/google";

import ProjectCreateForm from "~/components/project/ProjectCreateForm";

import styles from "~/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function ProjectCreate() {
  return (
    <>
      <Head>
        <title>AlmostDone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ProjectCreateForm />
      </main>
    </>
  );
}
